import { Chakra_Petch } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layouts/Layout";

const inter = Chakra_Petch({ subsets: ["latin"],weight:['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout >
        {children}
        </Layout>
        </body>
    </html>
  );
}
